name: charts_flutter
version: 0.8.3
description: Material Design charting library for flutter.
author: Charts Team <charts_flutter@google.com>
homepage: https://github.com/google/charts

environment:
  sdk: '>=1.23.0 <3.0.0'

dependencies:
  # Workaround to use this forked version of charts_flutter from git.
  charts_common:
    git:
      url: https://github.com/amdocs-iot-mobile/charts_common.git
      ref: v0.8.2-doxi

  collection: ^1.14.5
  flutter:
    sdk: flutter
  intl: '>=0.15.2 < 0.17.0'
  logging: any
  meta: ^1.1.1


dev_dependencies:
  mockito:
  flutter_test:
    sdk: flutter
  test: ^1.3.0
